version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angularjs-with-gulp-app
    volumes: 
      - ".:/workspace"
    ports:
      - "8081:8080"
    tty: true